### ISSUE TITLE
Could not decrypt SOPS file that contains multiple documents

### ISSUE THREAD

**Issue by yujunz** [signageos/vscode-sops#23]
Errors when opening yaml file with multiple documents

```
Could not decrypt SOPS file <redacted>: Source contains multiple documents; please use YAML.parseAllDocuments()
```

e.g.

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
...
```
