### ISSUE TITLE
Decrypt dotenv files

### ISSUE THREAD

**Issue by vterdunov** [signageos/vscode-sops#41]
Hi, Thanks for the extension.

Is it possible to work with `dotenv` files?

I created a dotenv file
```bash
KEY=value
KEY2=value2
```
Then encryped it `sops -e -i enc.env`.
My `.sops.yaml` is
```yaml
---
creation_rules:
  - path_regex: \.enc\.yaml$
    encrypted_regex: '^(data|stringData)$'
    pgp: >-
      <myGPGkeID>

  - path_regex: enc\.env$
    pgp: >-
      <myGPGkeID>
```
However autodecrypt doesn't work.
