### ISSUE TITLE
failure to access Azure KeyVault when not logged in via azcli

### ISSUE THREAD

**Issue by joeypiccola** [signageos/vscode-sops#55]
I'm having issues using SOPS with Azure's KeyVault. With the following `.sops.yaml` and `.envrc` files I can manually run the following command to both encrypt and decrypt secrets. This is leveraging a service principal via the env vars listed in my `.envrc`.

`sops -e -i colors/config.sops.yaml`
`sops --decrypt --in-place colors/config.sops.yaml`

**.envrc**
```plaintext
export AZURE_TENANT_ID=***
export AZURE_CLIENT_ID=***
export AZURE_CLIENT_SECRET=***
```

**.sops.yaml**
```yaml
---
creation_rules:
  - path_regex: (colors|fruits)/.*\.sops\.ya?ml
    encrypted_regex: "((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))"
    azure_keyvault: https://removed.vault.azure.net/keys/sops-key/removed-string
```

However, when using the VSCode extension [signageos/vscode-sops](https://github.com/signageos/vscode-sops) it appears to be trying to use SOPS' default azure auth method `cli`. This is discussed in the SOPS docs under [encrypting-using-azure-key-vault](https://github.com/mozilla/sops#encrypting-using-azure-key-vault). The SOPS docs discuss setting the env var `AZURE_AUTH_METHOD`, I've tried all the options but the extension continues to throw the following error. 

> Invoking Azure CLI failed with the following error: ERROR:
>       | No subscription found. Run 'az account set' to select a
>       | subscription.

When I do login `az login` with my own account (not the service principal with the access policy to the KeyVault) I then get this error detailing an `oid` of my own account (`oid=removed-68`). I'd prefer not to have to login with the service principal.  

> Group 0: FAILED
>   https://removed.vault.azure.net/keys/sops-key/removed-string: FAILED
>     - | Error decrypting key: keyvault.BaseClient#Decrypt: Failure
>       | responding to request: StatusCode=403 -- Original Error:
>       | autorest/azure: Service returned an error. Status=403
>       | Code="Forbidden" Message="The user, group or application
>       | 'appid=removed-46;oid=removed-68;numgroups=1;iss=https://sts.windows.net/removed/'
>       | does not have keys decrypt permission on key vault

Curious where I went wrong or if this is a bug with the extension.
