### ISSUE TITLE
aws-vault usage

### ISSUE THREAD

**Issue by mariusrugan** [signageos/vscode-sops#61]
Hi, 
thanks for your work first and foremost, it's amazing to have this kind of tooling and not to do CLI all day long :) 

I'm stuck in using it with aws-vault, where aws-vault is the primary "binary" that fetches session token and wrangles profiles.

this works:

```sh
aws-vault exec MY-PROFILE-NAME -t TOKEN -- sops secret.sops.yaml
```

How can i make the extension do this?

I'm using this approach to get the token even in my kubeconfig, 
as a part of ```command```

```yaml
  - name: arn:aws:eks:eu-west-1:12345:cluster/CLUSTER-ID
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        args:
          - -c
          - aws-vault exec MY-PROFILE-NAME -- aws --region eu-west-1 eks get-token
            --cluster-name CLUSTER-ID
        command: sh
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
        
```
thanks in advance!
