### ISSUE TITLE
Feature Request: Support Hashicorp Vault

### ISSUE THREAD

**Issue by Ryan-McD** [signageos/vscode-sops#64]
Given that SOPS supports Hashicorp vault, please consider supporting it's use with your plugin.

**Comment by dides82** [comment]
Hi @Ryan-McD 
I managed to get the extension working by using a .sops.yaml file configured to use Hashicorp vault:
```
creation_rules:
  - path_regex: test_hc.lab.yml
    hc_vault_transit_uri: http://localhost:8200/v1/sops/keys/lab
  - path_regex: test_hc.prd.yml
    hc_vault_transit_uri: http://localhost:8200/v1/sops/keys/prd
    encrypted_regex: "^(password)$"
```

and starting VSCode with the VAULT_TOKEN environment variable (VAULT_TOKEN=$VAULT_TOKEN code .) so that credentials are passed to VSCode.
It is obviously a workaround and the VAULT_TOKEN environment variable should be managed by the extension, but it works.

Hope this helps.

KR
